version: 0.2

phases:
  install:
    # If you're using Docker in your build environment, you might not need to specify the runtime version.
    # Docker is pre-installed in CodeBuild environments, but you can explicitly install it here if needed.
    commands:
      - echo Installing Docker...
      - yum install -y docker  # If you're using a custom image that does not have Docker pre-installed (skip this if using standard CodeBuild image)

  build:
    commands:
      - echo "Building the Docker image..."
      # Step 1: Get the ECR login password
      - aws ecr get-login-password --region us-east-1 > password.txt
      # Step 2: Log in to ECR with the password
      - docker login --username AWS --password-stdin 574844545380.dkr.ecr.us-east-1.amazonaws.com < password.txt
      # Step 3: Clean up the password file
      - rm -f password.txt
      # Build the Docker image
      - docker build -t 574844545380.dkr.ecr.us-east-1.amazonaws.com/my-app:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      # Push the Docker image to ECR
      - docker push 574844545380.dkr.ecr.us-east-1.amazonaws.com/my-app:$CODEBUILD_RESOLVED_SOURCE_VERSION
